export * from './Backoffice/BackOfficeDashboard'
export * from './Backoffice/OrganizationInfo'
export * from './Register/Register'
export * from './News/News'
export * from './News/BackOffice/NewsTable'
